### ISSUE TITLE
Bug: Cursor Is Slightly Off

### ISSUE THREAD

**Issue by mcmah309** [kaboc/flutter_custom_text#60]
When testing the markdown custom text in the example on web and android, the cursor is slightly above where it should be.

https://github.com/kaboc/flutter_custom_text/assets/56412856/59f379b4-2c59-4994-919f-a1ebb0c1a19e

Flutter 3.19.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bae5e49bc2 (8 weeks ago) • 2024-02-13 17:46:18 -0800
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1

**Comment by kaboc** [comment]
Hi, thank you for reporting this. I was aware of it but thinking it was a Flutter bug, and I'm now pretty sure it is a bug of this package. I'll probably be able to fix it within a few days, so please be patient.

If you need a quick workaround before the fix arrives, just try passing a proper height to `cursorHeight` of TextField / TextFormField.

**Comment by kaboc** [comment]
Fixed in 2.0.2. 😉
